// ignore_for_file: file_names

import '../productModel.dart';

final dummyProducts = [
  ProductModel(
    previewImage: 'assets/images/girl.jpg',
    productName: 'Product 1',
    productPrice: '350',
    productDescription: 'Description 1',
    productCategory: 'Category 1',
    productStore: 'Store 1',
    productRating: 3,
    productLocation: 'Location 1',
  ),
  ProductModel(
    previewImage: 'assets/images/girl.jpg',
    productName: 'Product 1',
    productPrice: '150',
    productDescription: 'Description 1',
    productCategory: 'Category 1',
    productStore: 'Store 1',
    productRating: 1,
    productLocation: 'Location 1',
  ),
  ProductModel(
    previewImage: 'assets/images/girl.jpg',
    productName: 'Product 1',
    productPrice: '500',
    productDescription: 'Description 1',
    productCategory: 'Category 1',
    productStore: 'Store 1',
    productRating: 1,
    productLocation: 'Location 1',
  ),
  ProductModel(
    previewImage: 'assets/images/girl.jpg',
    productName: 'Product 1',
    productPrice: 'Price 1',
    productDescription: 'Description 1',
    productCategory: 'Category 1',
    productStore: 'Store 1',
    productRating: 1,
    productLocation: 'Location 1',
  ),
  ProductModel(
    previewImage: 'assets/images/girl.jpg',
    productName: 'Product 1',
    productPrice: 'Price 1',
    productDescription: 'Description 1',
    productCategory: 'Category 1',
    productStore: 'Store 1',
    productRating: 1,
    productLocation: 'Location 1',
  ),
  ProductModel(
    previewImage: 'assets/images/girl.jpg',
    productName: 'Product 1',
    productPrice: 'Price 1',
    productDescription: 'Description 1',
    productCategory: 'Category 1',
    productStore: 'Store 1',
    productRating: 1,
    productLocation: 'Location 1',
  ),
  ProductModel(
    previewImage: 'assets/images/girl.jpg',
    productName: 'Product 1',
    productPrice: 'Price 1',
    productDescription: 'Description 1',
    productCategory: 'Category 1',
    productStore: 'Store 1',
    productRating: 1,
    productLocation: 'Location 1',
  ),
];
